In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('data/nuforc_reports.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136940 entries, 0 to 136939
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   summary         136866 non-null  object
 1   city            136562 non-null  object
 2   state           127595 non-null  object
 3   date_time       134272 non-null  object
 4   shape           131018 non-null  object
 5   duration        130451 non-null  object
 6   stats           136940 non-null  object
 7   report_link     136940 non-null  object
 8   text            136902 non-null  object
 9   posted          134272 non-null  object
 10  city_latitude   110136 non-null  float64
 11  city_longitude  110136 non-null  float64
dtypes: float64(2), object(10)
memory usage: 12.5+ MB

In [3]:
df

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
0,Viewed some red lights in the sky appearing to...,Visalia,CA,2021-12-15T21:45:00,light,2 minutes,Occurred : 12/15/2021 21:45 (Entered as : 12/...,http://www.nuforc.org/webreports/165/S165881.html,Viewed some red lights in the sky appearing to...,2021-12-19T00:00:00,36.356650,-119.347937
1,Look like 1 or 3 crafts from North traveling s...,Cincinnati,OH,2021-12-16T09:45:00,triangle,14 seconds,Occurred : 12/16/2021 09:45 (Entered as : 12/...,http://www.nuforc.org/webreports/165/S165888.html,Look like 1 or 3 crafts from North traveling s...,2021-12-19T00:00:00,39.174503,-84.481363
2,seen dark rectangle moving slowly thru the sky...,Tecopa,CA,2021-12-10T00:00:00,rectangle,Several minutes,Occurred : 12/10/2021 00:00 (Entered as : 12/...,http://www.nuforc.org/webreports/165/S165810.html,seen dark rectangle moving slowly thru the sky...,2021-12-19T00:00:00,NaN,NaN
3,"One red light moving switly west to east, beco...",Knoxville,TN,2021-12-10T19:30:00,triangle,20-30 seconds,Occurred : 12/10/2021 19:30 (Entered as : 12/...,http://www.nuforc.org/webreports/165/S165825.html,"One red light moving switly west to east, beco...",2021-12-19T00:00:00,35.961561,-83.980115
4,"Bright, circular Fresnel-lens shaped light sev...",Alexandria,VA,2021-12-07T08:00:00,circle,NaN,Occurred : 12/7/2021 08:00 (Entered as : 12/0...,http://www.nuforc.org/webreports/165/S165754.html,"Bright, circular Fresnel-lens shaped light sev...",2021-12-19T00:00:00,38.798958,-77.095133
...,...,...,...,...,...,...,...,...,...,...,...,...
136935,Huge black triangle with 3-4 lights on the sid...,Kennewick,WA,2021-02-28T08:20:00,triangle,15 Seconds,Occurred : 2/28/2021 08:20 (Entered as : 02/2...,http://www.nuforc.org/webreports/162/S162246.html,Huge black triangle with 3-4 lights on the sid...,2021-03-02T00:00:00,46.178823,-119.162978
136936,It was a cylinder shaped craft that appeared o...,Kissimmee,FL,2021-04-12T10:20:00,cylinder,3 seconds,Occurred : 4/12/2021 10:20 (Entered as : 04/1...,http://www.nuforc.org/webreports/162/S162692.html,It was a cylinder shaped craft that appeared o...,2021-04-23T00:00:00,28.255035,-81.429492
136937,Beautiful lights flying intimately over the so...,Denver,CO,2021-03-01T00:15:00,light,3 minutes,Occurred : 3/1/2021 00:15 (Entered as : 03/01...,http://www.nuforc.org/webreports/162/S162305.html,Beautiful lights flying intimately over the so...,2021-03-31T00:00:00,39.745126,-104.959346
136938,"3/15/21 in Mojave area fwy 14 or 58, close to ...",Mojave,CA,2021-03-15T21:00:00,flash,2-3 seconds,Occurred : 3/15/2021 21:00 (Entered as : 3/15...,http://www.nuforc.org/webreports/162/S162474.html,"3/15/21 in Mojave area fwy 14 or 58, close to ...",2021-03-31T00:00:00,35.097900,-118.130200
136939,"Miller State Park UFO sighting, 900sqf object ...",Peterborough,NH,2021-03-25T20:05:00,oval,30 seconds,Occurred : 3/25/2021 20:05 (Entered as : 03/2...,http://www.nuforc.org/webreports/162/S162507.html,"Miller State Park UFO sighting, 900sqf object ...",2021-03-31T00:00:00,42.866500,-71.960500

In [4]:
df["summary"].value_counts()

MADAR Node 142                                                                                                                            59
MADAR Node 119                                                                                                                            59
MADAR Node 143                                                                                                                            50
MADAR Node 100                                                                                                                            48
((NUFORC Note:  No information provided by witness.  PD))                                                                                 44
                                                                                                                                          ..
Many colored lights flew into a strange formation turned into sideways discs (about 9) and lit up in all colors, blinking at eachother     1
Cylinder shaped UFO that came to my wedding!                                                                                               1
One bright large bright light which had been stationary for a 10 minutes traveled at very hight speed to a 2nd more distant light.         1
Triangular light formation suspended high in air                                                                                           1
UFO appeared out of nowhere in the sky. It was ascending upwards.  ((Starlink satellites???))                                              1
Name: summary, Length: 134123, dtype: int64

In [5]:
df.describe()

       city_latitude  city_longitude
count  110136.000000   110136.000000
mean       38.704608      -95.185792
std         5.752186       18.310088
min       -32.055500     -170.494000
25%        34.238375     -113.901810
50%        39.257500      -89.161450
75%        42.317739      -80.363444
max        64.845276      130.850580

In [29]:
df.groupby('shape').size().sort_values(ascending=False).to_frame()

               0
shape
light      27871
circle     14438
triangle   12323
fireball    9602
other       9412
unknown     9318
sphere      8912
disk        8127
oval        5944
formation   4568
cigar       3350
changing    3348
flash       2398
rectangle   2348
cylinder    2138
diamond     1978
chevron     1574
teardrop    1183
egg         1182
cone         545
cross        439
delta         11
round          2
crescent       2
pyramid        1
hexagon        1
flare          1
dome           1
changed        1

In [ ]:
def split_train_test(data, test_ratio):
    shuffled_indices = np.random.permutation(len(data))
    test_set_size = int(len(data) * test_ratio)
    test_indices = shuffled_indices[:test_set_size]
    train_indices = shuffled_indices[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

np.random.seed(42)
train_set, test_set = split_train_test(df, 0.2)